### ISSUE TITLE
User Registration Validation

### ISSUE THREAD

**Issue by esron** [count-on-us/api#1]
Validate user registration request.

The request must have the following fields with their respective types and constrains:

- **name** - The user name, must be a string;
- **email** - The user email, must be a valid email;
- **password** - The user password, must be at least 6 characters in length, at least one number and one especial character.
- **profession** - The user professional specialty, must be one of: [Psicólogo, Psiquiatra, Psicanalista].
- **licenseNumber** - The user license number in their professional board in the formart ####/UF, where '#' represents digits and UF represents the brazilian state of the concil.

**Comment by Gabrielr2508** [comment]
I think that the licenseNumber hasn't a specific format. It's hard to validate.

**Comment by esron** [comment]
@Gabrielr2508 I need to do more research on that.

**Comment by esron** [comment]
Apparently the CRM, CREA, CRO and other kinds of licence number are only a incremental identifier. But they are divided per brazilian state.

I think that we can simple receive something that pass the following regex:

`([\w]+|[\d]+)\/[A-Z][A-Z]`

Thus, any alphanumeric string, a '/' character and the UF, that can be any two uppercase letters, for the sake of simplicity.
